# Lista de patrones sensibles y su reemplazo

SENSITIVE_PATTERNS += [
    (r"\bES\d{2}\s?\d{4}\s?\d{4}\s?\d{2}\s?\d{10}\b", "### IBAN ###"),
    (r"\b\d{4}\s?\d{4}\s?\d{2}\s?\d{10}\b", "### CCC ###"),
    (r"\b[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?\b", "### SWIFT/BIC ###"),
    (r"\b(?:\d[ -]*?){13,19}\b", "### TARJETA ###"),
    (r"\b(?:CVV|CVC|SEC)[\s:]?\d{3,4}\b", "### CVV ###"),
    (r"\b(?:ref\.?|n[úu]mero de referencia)[:\s]*\d{8,20}\b", "### REF. BANCARIA ###"),
    (r"\b(?:bizum|paypal|wallet)[\s:]?\d{6,15}\b", "### WALLET ###"),
    (r"\b\d{8}[A-HJ-NP-TV-Z]\b", "### DNI ###"),
    (r"\b[XYZ]\d{7}[A-Z]\b", "### NIE ###"),
    (r"\b[ABCDEFGHJKLMNPQRSUVW]\d{7}[0-9A-J]\b", "### NIF ###"),
    (r"\b\d{2}\s?\d{8,10}\b", "### SEG. SOCIAL ###"),
    (r"\b\d{2}[- ]?\d{8,10}\b", "### NAF ###"),
    (r"\b\d{10}\b", "### SIP ###"),
    (r"\b[A-Z]{3}\d{6}\b", "### PASAPORTE ###"),
    (r"\b[XYZ][- ]?\d{7}[- ]?[A-Z]\b", "### NIE (VAR) ###"),
    (r"\b(6|7|9)\d{2}[- ]?\d{3}[- ]?\d{3}\b", "### TELÉFONO ###"),
    (r"\+34[- ]?(6|7|9)\d{2}[- ]?\d{3}[- ]?\d{3}\b", "### TELÉFONO ES ###"),
    (r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b", "### EMAIL ###"),
    (r"(?<!\w)@[\w.]{3,30}\b", "### USUARIO ###"),
    (r"\buser(name)?[:=]?\s?[A-Za-z0-9_.-]{3,30}\b", "### USERNAME ###"),
    (r"https?://(www\.)?(instagram\.com|linkedin\.com|facebook\.com|twitter\.com|t\.me)/[A-Za-z0-9_.-]+", "### PERFIL RED SOCIAL ###"),
    (r"https?://t\.me/[\w.]+", "### TELEGRAM ###"),
    (r"\b(Calle|Avda|Avenida|Plaza|Paseo|Ctra|Carretera)[\s\w\dººº\-]+,\s?\d+[^\d]?\b", "### DIRECCIÓN ###"),
    (r"\b(0[1-9]|[1-4]\d|5[0-2])\d{3}\b", "### CP ###"),
    (r"(pass(word)?|contraseña|pwd)\s*[:=]\s*['\"]?.{4,50}['\"]?", "### CONTRASEÑA ###"),
    (r"\b[a-zA-Z0-9]{24,128}\b", "### TOKEN/API KEY ###"),
    (r"-----BEGIN [A-Z ]{5,50}KEY-----[\s\S]+?-----END [A-Z ]{5,50}KEY-----", "### CLAVE PRIVADA ###"),
    (r"\b\d{4,8}\b", "### CÓDIGO ###"),
    (r"(palabra\s+de\s+recuperación|recovery\s+phrase|seed\s+phrase)[:\s]+([\w]+\s+){10,24}", "### SEED PHRASE ###"),
    (r"(api[_-]?key|secret|access[_-]?token)\s*[:=]\s*['\"]?.{8,128}['\"]?", "### CLAVE/API ###"),
    (r"\b(Calle|Avda|Avenida|C/|Plaza|Paseo|Camino|Carretera)\s+[\w\s]+,\s*\d{1,5}(?:[\s,]+[A-ZÁÉÍÓÚÑa-záéíóúñ\s]+)?", "### DIRECCIÓN ###"),
    (r"\b(0[1-9]|[1-4][0-9]|5[0-2])\d{3}\b", "### CÓDIGO POSTAL ###"),
    (r"\b-?\d{1,3}\.\d{3,},\s*-?\d{1,3}\.\d{3,}\b", "### COORDENADAS GPS ###"),
    (r"\b\d{5}\s+(Guadalajara|Madrid|Barcelona|Valencia|Zaragoza|Toledo|Sevilla|Bilbao|Málaga|Granada|Murcia)\b", "### CIUDAD ###"),
    (r"https?:\/\/(www\.)?(google\.)?maps\.google\.com\/[^\s]+", "### URL DE MAPA ###"),
    (r"\b(C\/|Calle|Avda|Avenida|Plaza|Paseo)\s+[\w\s]+,\s*\d{1,5}(,\s*\d+[ºoª]?[A-Za-z]?)?", "### DIRECCIÓN ###"),
    (r"\b(\d{10,16}[A-Z]?)\b", "### TARJETA SANITARIA ###"),
    (r"\b(diabetes|hipertensión|cáncer|asma|epilepsia|esclerosis|alzh[eé]imer|parkinson|trastorno|ansiedad|depresión|autismo|TDAH|VIH|sida)\b", "### ENFERMEDAD ###"),
    (r"\b(paracetamol|ibuprofeno|diazepam|tramadol|lorazepam|omeprazol|sertralina|metformina|rivotril|valium|lexatin|zolpidem)\b", "### MEDICAMENTO ###"),
    (r"\b(análisis de sangre|resonancia|PCR|ecografía|biopsia|colonoscopia|mamografía|test rápido|radiografía|RMN|TAC)\b", "### PRUEBA MÉDICA ###"),
    (r"\b(glucosa|colesterol|tensi[oó]n|hematocrito|hemoglobina|frecuencia cardíaca|ritmo sinusal|oxigenación)\s*\d+([.,]\d+)?\s*(mg/dL|mmHg|%)?", "### DATO CLÍNICO ###"),
    (r"\b(historial cl[ií]nico|diagn[oó]stico|tratamiento prescrito|consentimiento informado|receta electr[oó]nica|informe m[eé]dico)\b", "### INFORME MÉDICO ###"),
    (r"\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b", "### UUID ###"),
    (r"\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\b", "### MAC ###"),
    (r"\b(?:\d{1,3}\.){3}\d{1,3}\b", "### IP ###"),
    (r"\b(AIza[0-9A-Za-z\-_]{35}|sk_live_[0-9a-zA-Z]{24}|sk_test_[0-9a-zA-Z]{24}|AKIA[0-9A-Z]{16})\b", "### CLAVE API ###"),
    (r"\b(confidencial|privado|uso interno|restringido)\b", "### AVISO DE CONFIDENCIALIDAD ###"),
    (r"\b\d{2}[\s-]?\d{8}[\s-]?\d\b", "### NÚMERO SS ###"),
    (r"\b(secret\.key|passwords?\.txt|config\.env|.env\.local)\b", "### FICHERO SENSIBLE ###"),
]